# Build Classification Model

In [1]:
import pandas as pd
cuisines_df = pd.read_csv("../data/cleaned_cuisines.csv")
cuisines_df.head()

c:\Users\Dell\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

,Unnamed: 0,cuisine,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,indian,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [2]:
cuisines_label_df = cuisines_df['cuisine']
cuisines_label_df.head()

0    indian
1    indian
2    indian
3    indian
4    indian
Name: cuisine, dtype: object

In [3]:
cuisines_feature_df = cuisines_df.drop(['Unnamed: 0', 'cuisine'], axis=1)
cuisines_feature_df.head()

,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,artichoke,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, precision_score, confusion_matrix,classification_report, precision_recall_curve
import numpy as np

In [5]:
X_train, X_test, y_train, y_test = train_test_split(cuisines_feature_df,cuisines_label_df,test_size=.33)

In [6]:
C = 10
# Create different classifiers.
classifiers = {
    'Linear SVC': SVC(kernel='linear', C=C, probability=True, random_state=0),
    'KNN classifier': KNeighborsClassifier(C),
    'SVC': SVC(),
    'RFST': RandomForestClassifier(n_estimators=100),
    'ADA': AdaBoostClassifier(n_estimators=100)
}

In [7]:
# Model training using the Linear SVC and report:
n_classifier = len(classifiers)
for index, (name, classifiers) in enumerate(classifiers.items()):
    classifiers.fit(X_train, np.ravel(y_train))
    y_pred = classifiers.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    print("Accuracy (train) for %s: %0.1f%% " % (name, accuracy * 100))
    print(classification_report(y_test,y_pred))

Accuracy (train) for Linear SVC: 80.1%
              precision    recall  f1-score   support

     chinese       0.71      0.71      0.71       267
      indian       0.87      0.91      0.89       257
    japanese       0.80      0.81      0.80       254
      korean       0.83      0.78      0.80       254
        thai       0.80      0.80      0.80       287

    accuracy                           0.80      1319
   macro avg       0.80      0.80      0.80      1319
weighted avg       0.80      0.80      0.80      1319

Accuracy (train) for KNN classifier: 71.6%
              precision    recall  f1-score   support

     chinese       0.59      0.74      0.66       267
      indian       0.81      0.82      0.81       257
    japanese       0.66      0.85      0.74       254
      korean       0.91      0.53      0.67       254
        thai       0.76      0.65      0.70       287

    accuracy                           0.72      1319
   macro avg       0.74      0.72      0.72      1319
weighted avg       0.74      0.72      0.72      1319

Accuracy (train) for SVC: 82.3%
              precision    recall  f1-score   support

     chinese       0.74      0.72      0.73       267
      indian       0.89      0.93      0.91       257
    japanese       0.83      0.82      0.83       254
      korean       0.87      0.81      0.84       254
        thai       0.80      0.85      0.82       287

    accuracy                           0.82      1319
   macro avg       0.82      0.82      0.82      1319
weighted avg       0.82      0.82      0.82      1319

Accuracy (train) for RFST: 83.9%
              precision    recall  f1-score   support

     chinese       0.80      0.75      0.77       267
      indian       0.90      0.91      0.91       257
    japanese       0.81      0.82      0.82       254
      korean       0.86      0.83      0.85       254
        thai       0.82      0.88      0.85       287

    accuracy                           0.84      1319
   macro avg       0.84      0.84      0.84      1319
weighted avg       0.84      0.84      0.84      1319

Accuracy (train) for ADA: 69.8%
              precision    recall  f1-score   support

     chinese       0.53      0.54      0.54       267
      indian       0.83      0.86      0.85       257
    japanese       0.70      0.65      0.68       254
      korean       0.70      0.73      0.72       254
        thai       0.73      0.70      0.72       287

    accuracy                           0.70      1319
   macro avg       0.70      0.70      0.70      1319
weighted avg       0.70      0.70      0.70      1319